name: Deploy Frontend
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker login -u mayurbhave -p Insp!re@2025
      - run: docker build -t mayurbhave/docker-react -f Dockerfile.dev .
      - run: docker run -e CI=true mayurbhave/docker-react npm test

      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v18
        with:
          application_name: frontend
          environment_name: Frontend-env
          existing_bucket_name: elasticbeanstalk-us-east-1-292256264782
          region: us-east-1
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip
